#!/bin/sh

SCRIPT_DIR=$(cd "$(dirname $0)"; pwd)
. $SCRIPT_DIR/../config/version.sh

cat << EOL > ${SCRIPT_DIR}/version.sh
#!/bin/sh
# DO NOT EDIT! This file is automatically generated by setup.sh

DEBIAN11_VERSION="${DEBIAN11_VERSION}"
DEBIAN11_AMD64_CHECKSUM="$(curl http://cdimage.debian.org/cdimage/archive/${DEBIAN11_VERSION}/amd64/iso-dvd/SHA512SUMS | head -1 | awk '{print $1}')"
DEBIAN11_ARM64_CHECKSUM="$(curl http://cdimage.debian.org/cdimage/archive/${DEBIAN11_VERSION}/arm64/iso-dvd/SHA512SUMS | head -1 | awk '{print $1}')"

DEBIAN12_VERSION="${DEBIAN12_VERSION}"
DEBIAN12_AMD64_CHECKSUM="$(curl http://cdimage.debian.org/cdimage/release/${DEBIAN12_VERSION}/amd64/iso-dvd/SHA512SUMS | head -1 | awk '{print $1}')"
DEBIAN12_ARM64_CHECKSUM="$(curl http://cdimage.debian.org/cdimage/release/${DEBIAN12_VERSION}/arm64/iso-dvd/SHA512SUMS | head -1 | awk '{print $1}')"
EOL
