FROM @BASE_IMAGE@
LABEL maintainer="Synge Todo"
ENV DEBIAN_FRONTEND=noninteractive

COPY script/build-deb.sh /root/
COPY script/.quiltrc /root/

RUN apt-get update && apt-get -y upgrade \
  && apt-get install -y \
       build-essential \
       cdbs \
       cmake \
       curl \
       devscripts \
       gfortran \
       git \
       liblapack-dev \
       mpi-default-dev \
       quilt \
       vim \
  && curl http://jaist.dl.sourceforge.net/project/materiappslive/Debian/sources/setup.sh | /bin/sh \
  && apt-get update \
  && rm -rf /var/lib/apt/lists/*
