#!/bin/sh

set -e

lb build noauto "${@}" 2>&1 | tee build.log
echo $? | tee -a build.log

ISO_NAME="MateriAppsLive-$(cat materiapps_version)-$(dpkg --print-architecture).hybrid.iso"
if [ -f binary.hybrid.iso ]; then
  echo "moving binary.hybrid.iso to ${ISO_NAME}..." 2>&1 | tee -a build.log
  mv -f binary.hybrid.iso ${ISO_NAME}
elif [ -f live-image-$(dpkg --print-architecture).hybrid.iso ]; then
  echo "moving live-image-$(dpkg --print-architecture).hybrid.iso to ${ISO_NAME}..." 2>&1 | tee -a build.log
  mv -f live-image-$(dpkg --print-architecture).hybrid.iso ${ISO_NAME}
fi
if [ -d /data ]; then
  echo "moving ${ISO_NAME} to /data/${ISO_NAME}..." 2>&1 | tee -a build.log
  mv -f ${ISO_NAME} /data/${ISO_NAME}
  ls -l /data/${ISO_NAME} 2>&1 | tee -a build.log
fi
date 2>&1 | tee -a build.log
echo "done" 2>&1 | tee -a build.log
